name: 01-conditions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Print message if condition is true
      if: ${{ true }}
      run: echo "This message will be printed because the condition is true"

    - name: Print message if condition is false
      if: ${{ false }}
      run: echo "This message will not be printed because the condition is false"