name : 03-usingcache

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Use cache for build'
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        
      - name: setup cache
        id: cache
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: idnjs-build-${{ hashFiles('react-app/package-lock.json') }}
      - name: install dependencies
        if: ${{ !steps.cache.outputs.cache-hit == 'true' }}
        run: npm install
      - name: build the application
        run: npm run build
      - name: test the application
        run: npm run test
      - name: deploy the application to prod
        run: echo "Deploying the application to production environment..."
      - name: print cache usage
        run: |
          echo "Cache was used: ${{ steps.cache.outputs.cache-hit }}"