name: contexts
run-name: run on the debug ${{ github.debug }}

on: 
  workflow_dispatch:
    inputs:
        debug:
          description: 'Debug value'
          required: false
          default: 'default debug value'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Print context information
      run: |
        echo "GITHUB_REPOSITORY: ${{ github.repository }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_ACTOR: ${{ github.actor }}"
        echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
        echo "GITHUB_RUN_ID: ${{ github.run_id }}"5
        echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
        echo "GITHUB_JOB: ${{ github.job }}"
    
    - name: retrieve variable from env
      run: |
        echo "variable from env: ${{ vars.MY_VAR }}"
