name: build demo
on:
  push
jobs:
<<<<<<< HEAD
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: demo-01-build
          path: target/*.jar
=======
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Build with Gradle
          run: echo "Hello world"
>>>>>>> db85c7e90d3111648d82002f1b7fa23da9619fcb
